[package]
name = "tipb"
version = "0.0.1"
edition = "2018"

[features]
default = ["protobuf-codec"]
protobuf-codec = []
prost-codec = ["prost", "prost-derive", "bytes", "lazy_static"]
gen = []

[lib]
name = "tipb"

[dependencies]
protobuf = "2"
prost = { git = "https://github.com/danburkert/prost", rev = "1944c27c3029d01ff216e7b126d846b6cf8c7d77", optional = true }
prost-derive = { git = "https://github.com/danburkert/prost", rev = "1944c27c3029d01ff216e7b126d846b6cf8c7d77", optional = true }
bytes = { version = "0.4", optional = true }
lazy_static = { version = "1.3", optional = true }

[build-dependencies]
protobuf-build = "0.6"
